### ISSUE TITLE
a question about the equal error rate

### ISSUE THREAD

**Issue by l1amw** [TakHemlata/RawBoost-antispoofing#1]
hi, it's a great work, but there is a problem, i used the pre-trained model but found that the EER was about 11.7%, which is quite different from the data in your paper, 5.31%, if i remember correctly, could you please tell me if i did something wrong? Below is the score file.
[RawBoost_eval_CM_scores.txt](https://github.com/TakHemlata/RawBoost-antispoofing/files/8215142/RawBoost_eval_CM_scores.txt)

**Comment by TakHemlata** [comment]
Hi,

Thanks for your interest.

I checked EER performance for your above-attached scores file using performance measure code from ASVspoof 2021 challenge git repo (https://github.com/asvspoof-challenge/2021/tree/main/eval-package/LA/package-stage-1).

Results from your attached scores file:
min_tDCF: 0.3099
EER : 5.31 %
Which is exactly the same as our paper.

I also again tested my pre-trained model (provided in this repo) on 2021 LA data and got same results as above.

I suggest you before posting please double-check your results with correct codes.

thanks

Regards,
Hemlata

**Comment by TakHemlata** [comment]
I hope you get your answer. I am closing this issue.
